sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev
    - apache2-bin
    - apache2-data
    - apache2-dev

before_script:
  - curl -L https://cpanmin.us | sudo perl - --sudo App::cpanminus
  - sudo cpanm --quiet --notest --skip-satisfied CGI::Cookie
  - sudo cpanm --quiet --notest --skip-satisfied Apache::TestRun
  - cd ..
  - git clone https://github.com/SpiderLabs/ModSecurity.git
  - cd ModSecurity
  - git checkout v3/master
  - git submodule init
  - git submodule update
  - ./build.sh
  - ./configure --without-lmdb
  - make
  - sudo make install
  - pwd
  - cd -
  - cd ModSecurity-apache
  - pwd

script:
    - t/TEST.PL

